feat: write raw byte.
almindor/max7219 pull request #10
Opened 2023-12-11 21:04 UTC by 2e0byo

This is a simple passthrough to the method on the controller.  Most users probably won't want it, but when a max7219 is connected to a dot-matrix display and used as a display with `embedded_graphics` it may make sense to be able to address the display in the smallest possible unit.  (For instance, an efficient display updating algorithm can keep the previous state in a framebuffer and only send the commands needed to update those bytes which have changed.)

The alternative of making the connector public seems much more drastic.

Thanks for the library!

2023-12-12 17:00 UTC, almindor approved these changes
LGTM, thanks!

2023-12-12 17:01 UTC, almindor requested changes
Actually, sorry I always forget, could you please add a CHANGELOG entry?

2023-12-13 17:58 UTC, 2e0byo commented
Sure, I'll do it after work today.

2023-12-13 19:57 UTC, almindor approved these changes
ty

2023-12-13 19:58 UTC, merged